spring.application.name=visitas-medicas
server.port=8081
spring.datasource.url=jdbc:postgresql://visitas_db:5432/visitas_medicas
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
